steps:
  # Step 1: Build the Go application
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'main', './cmd/main.go']  # Ensure you are specifying the correct directory for main.go

  # Step 2: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-southwest1-docker.pkg.dev/acquired-subset-424910-i5/challenge-developer', '.']

  # Step 3: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-southwest1-docker.pkg.dev/acquired-subset-424910-i5/challenge-developer']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'asteroids'
      - '--image=europe-southwest1-docker.pkg.dev/acquired-subset-424910-i5/challenge-developer'
      - '--platform=managed'
      - '--region=europe-southwest1'
      - '--allow-unauthenticated'  # Ensure the service is publicly accessible

images:
  - 'europe-southwest1-docker.pkg.dev/acquired-subset-424910-i5/challenge-developer'